apiVersion: v1
kind: ConfigMap
metadata:
  name: metadata-config
data:
  default.yaml: |
    api:
      port: 8081
    serviceDiscovery:
      consul:
        address: http://consul-server.consul.svc.cluster.local:8500
