services:
  mySQL:
    image: mysql
    container_name: movieexample_db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: movieexample
    volumes:
      - ./database/:/var/lib/mysql

  dev-consul:
    image: hashicorp/consul
    container_name: dev-consul
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client='0.0.0.0'
    ports:
      - "8500:8500"
      - "8600:8600/udp"

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
