apiVersion: v1
kind: ConfigMap
metadata:
  name: rating-config
data:
  default.yaml: |
    api:
      port: 8082
    serviceDiscovery:
      consul:
        address: http://consul-server.consul.svc.cluster.local:8500
    kafka:
      address: http://kafka-cluster-kafka-brokers.kafka.svc.cluster.local:9092
      groupId: rating
      topic: ratings
