apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata
spec:
  replicas: 2
  selector:
    matchLabels:
      app: metadata
  template:
    metadata:
      labels:
        app: metadata
    spec:
      containers:
        - name: metadata
          image: metadata:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: metadata-vol
              mountPath: /app
          env:
            - name: DB_USERNAME
              valueFrom:
                secretRefKey:
                  name: metadata-db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretRefKey:
                  name: metadata-db-secret
                  key: DB_PASSWORD
      volumes:
        - name: metadata-vol
          configMap:
            - name: metadata-config
              items:
                - key: default.yaml
                  path: default.yaml
