apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating
  template:
    metadata:
      labels:
        app: rating
    spec:
      containers:
        - name: rating
          image: rating:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          volumeMounts:
            - name: rating-vol
              mountPath: /app
          env:
            - name: DB_USERNAME
              valueFrom:
                secretRefKey:
                  name: rating-db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretRefKey:
                  name: rating-db-secret
                  key: DB_PASSWORD
      volumes:
        - name: rating-vol
          configMap:
            name: rating-config
            items:
              - key: default.yaml
                path: default.yaml
